### ISSUE TITLE
Not able to share image via Instagram

### ISSUE THREAD

**Issue by Sharathnasa** [react-native-community/react-native-share#277]
Hi,

I have used the master branch to get the instagram share of the image to feed and story. I have also followed the latest read me file to integrate file provider. For the first time when i click share via instagram to feed or story, selected image is sharing. But if i come and click on share via instagram using feed or story, i'm getting the below exception.

```
06-10 18:46:56.173 14001-14016/io.fxpi.autocaptions E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading android.support.v4.content.FileProvider uri content://io.fxpi.autocaptions.provider/external_files/Download/1528636614038.png from pid=15089, uid=10600 requires the provider be exported, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:639)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:505)
        at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:496)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:424)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:302)
        at android.os.Binder.execTransact(Binder.java:682)
```

Please could you help me where i'm doing wrong

Regards,
Sharath

**Comment by Sharathnasa** [comment]
@jgcmarins But in the all share application menu, even we'll get feed and story option of the instagram right, there even if i do share of images or video 'n' number of time while coming back to app, not facing this issue. So the problem is with the direct share.

**Comment by ziahm** [comment]
Is the issue resolved already ?
