### ISSUE TITLE
Odd exception logged (but still works)

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-community/react-native-share#613]
### Steps to reproduce
I'm getting the following logged into logcat:
```
2019-10-26 14:51:47.334 12395-12415/com.zinspector3.dev E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://com.zinspector3.dev.provider/files-path/thumbnails/sketch_4663036438425913034a7b74ddc-0579-4400-8c6c-5b00f2b12ffb.png from pid=17727, uid=1000 requires the provider be exported, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:729)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
        at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:593)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:507)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:307)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```

Share still works, but I'm not sure why this is getting logged. This happens when sharing a file from the app's storage. It's curious that this happens even if `grantUriPermissions` is set to `true`.

I also have the following config:

Manifest:
```
<provider
          android:name="androidx.core.content.FileProvider"
          android:authorities="${applicationId}.provider"
          android:exported="false"
          android:grantUriPermissions="true">
          <meta-data
              android:name="android.support.FILE_PROVIDER_PATHS"
              android:resource="@xml/provider_paths"
            />
      </provider>
```

provider_paths:
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <cache-path name="cache-path" path="" />
    <external-path
        name="external_files"
        path="." />
    <files-path
        name="files-path"
        path="." /> <!-- Used to access into application data files -->
</paths>
```

Did I miss anything?

### Environment
- **React Native version**: 0.60.5
- **React Native platform + platform version**: Android 10

### react-native-share
**Version**: 2.0.0

**Comment by novemberborn** [comment]
FWIW, since my files are fairly small, I've resorted to accessing them as base64-encoded strings.

<details>
<summary>Expand to read a short rant. ❤️ to the maintainers regardless.</summary>

This does my head in though: I need one package to access the data and bridge it into JavaScript, and then bridge it back into this package, which ends up writing it to disk (the Downloads directory). Sharing from there works because I imagine every App is allowed to read from that directory, at the cost of a permissions dialog before my App is allowed to write there. It's not really a solution when the files are even slightly sensitive, however.
</details>

**Comment by jgcmarins** [comment]
> To me this suggests a race condition in how the permissions are granted on the intent.

It makes sense

**Comment by jgcmarins** [comment]
Any of you have a reproducible repository?

Or at least open a pull request with our [example](https://github.com/react-native-community/react-native-share/tree/master/example)

**Comment by novemberborn** [comment]
> Any of you have a reproducible repository?
> 
> Or at least open a pull request with our [example](https://github.com/react-native-community/react-native-share/tree/master/example)

Unfortunately this made us reconsider sharing files from our App, and we're now opening them in a browser instead. That and my relative inexperience with Android stuff means that I won't be able to help with that, sorry.

**Comment by jgcmarins** [comment]
@novemberborn, that's ok.
Thanks for you help \o/

**Comment by cr8tpro** [comment]
it's still not solved. same issue occurs for me as well.

**Comment by enosh94** [comment]
Same error here. but It works well sometimes.

**Comment by MateusAndrade** [comment]
> Same error here. but It works well sometimes.

Wich version are you using?

**Comment by enosh94** [comment]
> > Same error here. but It works well sometimes.
> 
> Wich version are you using?

0.60.5

**Comment by MateusAndrade** [comment]
> 0.60.5

And which react-native-share version are you using? Also, would you mind sharing the options that you are passing?

**Comment by dylan-westbury** [comment]
Also receiving this error too 

```
07-27 18:12:19.797  5386  5588 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://com.heyswysh.swysh.provider/external_files/Download/sticker.jpg from pid=5665, uid=10093 requires the provider be exported, or grantUriPermission()
07-27 18:12:19.797  5386  5588 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:631)
07-27 18:12:19.797  5386  5588 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:501)
07-27 18:12:19.797  5386  5588 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:492)
07-27 18:12:19.797  5386  5588 E DatabaseUtils: 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:420)
07-27 18:12:19.797  5386  5588 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:302)
07-27 18:12:19.797  5386  5588 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:697)
07-27 18:12:19.797  5665  5728 E StoryShareMediator: Exception in ExternalMediaImportCallable
07-27 18:12:19.797  5665  5728 E StoryShareMediator: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://com.heyswysh.swysh.provider/external_files/Download/sticker.jpg from pid=5665, uid=10093 requires the provider be exported, or grantUriPermission()
07-27 18:12:19.797  5665  5728 E StoryShareMediator: 	at android.os.Parcel.readException(Parcel.java:2004)
07-27 18:12:19.797  5665  5728 E StoryShareMediator: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
07-27 18:12:19.797  5665  5728 E StoryShareMediator: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
07-27 18:12:19.797  5665  5728 E StoryShareMediator: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:698)
07-27 18:12:19.797  5665  5728 E StoryShareMediator: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1410)
07-27 18:12:19.797  5665  5728 E StoryShareMediator: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1247)
07-27 18:12:19.797  5665  5728 E StoryShareMediator: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:967)
07-27 18:12:19.797  5665  5728 E StoryShareMediator: 	at X.97B.A00(:8)
07-27 18:12:19.797  5665  5728 E StoryShareMediator: 	at X.97C.A00(:12)
07-27 18:12:19.797  5665  5728 E StoryShareMediator: 	at X.97D.run(:52)
07-27 18:12:19.797  5665  5728 E StoryShareMediator: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-27 18:12:19.797  5665  5728 E StoryShareMediator: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-27 18:12:19.797  5665  5728 E StoryShareMediator: 	at java.lang.Thread.run(Thread.java:764)
07-27 18:12:19.797  5665  5728 E StoryShareMediator: 	at X.0Nv.run(:5)
```


```
<provider
        android:name="androidx.core.content.FileProvider"
        android:authorities="${applicationId}.provider"
        android:grantUriPermissions="true"
        android:exported="false">
      <meta-data
          android:name="android.support.FILE_PROVIDER_PATHS"
          android:resource="@xml/filepaths" />
    </provider>
```

```
const shareOptions = {
      method: Share.InstagramStories.SHARE_STICKER_IMAGE,
      stickerImage: SHARE_STAR_IMAGE_BASE64,
      backgroundBottomColor: '#FEFEFE',
      backgroundTopColor: '#FEFEFE',
      social: Share.Social.INSTAGRAM_STORIES,
      failOnCancel: false,
      forceDialog: true,
    };
    
    try {
      await Share.shareSingle(shareOptions);
    }
      //catch error when user does not share
    catch (err) {
      Alert.alert('Could not share to Instagram');
    }
```

**Comment by shaan-mephobic** [comment]
I too face this error. It works only on devices with se-linux set to permissive which can only be achieved with root permission now.
