### ISSUE TITLE
Fail to share file directly on Android

### ISSUE THREAD

**Issue by LuizFBrisighello** [react-native-community/react-native-share#718]
My application just closes after calling this function.
No errors gets logged.

```
  function _share (fileUrl) {
    let filePath = null
    const configOptions = {
      fileCache: true,
      path: RNFetchBlob.fs.dirs.DocumentDir + '/Boleto.pdf'
    }
    console.log('preparing to fetch')
    RNFetchBlob.config(configOptions)
      .fetch('GET', fileUrl)
      .then(async resp => {
        console.log('fetched')
        filePath = 'file:/' + resp.path() // returns file://data/user/0/com.my.app/files/Boleto.pdf
        console.log(filePath)
        const options = {
          url: filePath
        }
        console.log('preparing to share')
        try {
          await Share.open(options)
          console.log('shared')
          await RNFetchBlob.fs.unlink(filePath)
          console.log('removed')
        } catch (err) {
          console.log(err)
        }
      })
  }
```

`react-native`: 0.60.5
`react-native-share`: 3.0.0

**Comment by MateusAndrade** [comment]
Hey @LuizFBrisighello , would you mind sharing a your log after this error? 😄

**Comment by defranke** [comment]
I have the same issue. It works in an emulator, but on a Pixel 3 it crashes with the following exception:
`
2020-03-11 16:31:49.565 25833-25833/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: android:ui, PID: 25833
    java.lang.NullPointerException: url
        at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:133)
        at android.content.ContentResolver.getType(ContentResolver.java:716)
        at com.android.internal.app.ChooserActivity.displayImageContentPreview(ChooserActivity.java:959)
        at com.android.internal.app.ChooserActivity.displayContentPreview(ChooserActivity.java:879)
        at com.android.internal.app.ChooserActivity.access$2800(ChooserActivity.java:141)
        at com.android.internal.app.ChooserActivity$ChooserRowAdapter.createContentPreviewView(ChooserActivity.java:3128)
        at com.android.internal.app.ChooserActivity$ChooserRowAdapter.getView(ChooserActivity.java:3070)
        at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:224)
        at android.widget.AbsListView.obtainView(AbsListView.java:2405)
        at android.widget.ListView.makeAndAddView(ListView.java:2071)
        at android.widget.ListView.fillDown(ListView.java:797)
        at android.widget.ListView.fillFromTop(ListView.java:859)
        at android.widget.ListView.layoutChildren(ListView.java:1842)
        at android.widget.AbsListView.onLayout(AbsListView.java:2202)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at com.android.internal.widget.ResolverDrawerLayout.onLayout(ResolverDrawerLayout.java:957)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3185)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:726)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
`

On some other devices it works.

**Comment by sergchernata** [comment]
Same issue here - crash without any errors logged. Seems to be happening specifically when using `file://` in the url.

**Comment by MateusAndrade** [comment]
> Same issue here - crash without any errors logged. Seems to be happening specifically when using `file://` in the url.

Strang, would you mind testing our last version? Also, did you asked for access to the internal storage permission?

**Comment by sergchernata** [comment]
> Strang, would you mind testing our last version? Also, did you asked for access to the internal storage permission?

I'm on `3.1.1`, using `RNFS.DocumentDirectoryPath` and have the following permissions:

```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

**Comment by sergchernata** [comment]
Using `RNFS.CachesDirectoryPath` works, however, then I also run into the same issue as #475.

In which case, I need to comment out `RNFS.unlink` for the file to be attached to Gmail message.

#475 was closed but seems to still be an issue.

**Comment by ftlno** [comment]
Any news here? I am experiencing this now. How did you get around this @sergchernata ? Considering performing RNFS.unlink when the app is closed.. But this is not the ideal solution..
